server:
  port: 5067
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://qozzmvjz:1L0mYRORLK9hU8-W-9mvSaqTwZ9Y9QxP@batyr.db.elephantsql.com/qozzmvjz
    username: qozzmvjz
    password: 1L0mYRORLK9hU8-W-9mvSaqTwZ9Y9QxP
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      connectionTestQuery: SELECT 1 FROM DUAL
springdoc:
  swagger-ui:
    enabled: true